/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longlinkislong_gloop_dsa_NativeDSA */

#ifndef _Included_com_longlinkislong_gloop_dsa_NativeDSA
#define _Included_com_longlinkislong_gloop_dsa_NativeDSA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedFramebufferTexture1d
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedFramebufferTexture1d
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedFramebufferTexture2d
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedFramebufferTexture2d
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureParameteri
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureParameteri__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureParameterf
 * Signature: (IIIF)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureParameterf__IIIF
  (JNIEnv *, jclass, jint, jint, jint, jfloat);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglGenerateTextureMipmap
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglGenerateTextureMipmap__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglBindTextureUnit
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglBindTextureUnit__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureImage1d
 * Signature: (IIIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureImage1d__IIIIIIIIJ
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureImage1d
 * Signature: (IIIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureImage1d__IIIIIIIILjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureImage2d
 * Signature: (IIIIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureImage2d__IIIIIIIIILjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureImage2d
 * Signature: (IIIIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureImage2d__IIIIIIIIIJ
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureImage3d
 * Signature: (IIIIIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureImage3d__IIIIIIIIIILjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureImage3d
 * Signature: (IIIIIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureImage3d__IIIIIIIIIIJ
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglBlitNamedFramebuffer
 * Signature: (IIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglBlitNamedFramebuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglGetNamedBufferParameteri
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglGetNamedBufferParameteri
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglBindTextureUnit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglBindTextureUnit__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglGenerateTextureMipmap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglGenerateTextureMipmap__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureStorage3d
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureStorage3d
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureStorage2d
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureStorage2d
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureStorage1d
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureStorage1d
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureSubImage3d
 * Signature: (IIIIIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureSubImage3d
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureSubImage2d
 * Signature: (IIIIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureSubImage2d
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureSubImage1d
 * Signature: (IIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureSubImage1d
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureParameterf__IIF
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglTextureParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglTextureParameteri__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniformMatrix4d
 * Signature: (IIZLjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniformMatrix4d
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniformMatrix2d
 * Signature: (IIZLjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniformMatrix2d
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniformMatrix3d
 * Signature: (IIZLjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniformMatrix3d
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniformMatrix4f
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniformMatrix4f
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniformMatrix3f
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniformMatrix3f
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniformMatrix2f
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniformMatrix2f
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform4d
 * Signature: (IIDDDD)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform4d
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform3d
 * Signature: (IIDDD)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform3d
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform2d
 * Signature: (IIDD)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform2d
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform4i
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform3i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform3i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform1d
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform1d
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform2i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform2i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform1i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform1i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform4f
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform4f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform3f
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform3f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform2f
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform2f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglProgramUniform1f
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglProgramUniform1f
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglCopyNamedBufferSubData
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglCopyNamedBufferSubData
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglUnmapNamedBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglUnmapNamedBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglMapNamedBufferRange
 * Signature: (IJJILjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglMapNamedBufferRange
  (JNIEnv *, jclass, jint, jlong, jlong, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglGetNamedBufferSubData
 * Signature: (IJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglGetNamedBufferSubData
  (JNIEnv *, jclass, jint, jlong, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedBufferStorage
 * Signature: (IJI)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedBufferStorage__IJI
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedBufferSubData
 * Signature: (IJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedBufferSubData
  (JNIEnv *, jclass, jint, jlong, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedBufferData
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedBufferData__ILjava_nio_ByteBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedFramebufferTexture
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedFramebufferTexture
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedBufferReadPixels
 * Signature: (IIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedBufferReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglCreateFramebuffers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglCreateFramebuffers
  (JNIEnv *, jclass);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglCreateTextures
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglCreateTextures
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglCreateBuffers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglCreateBuffers
  (JNIEnv *, jclass);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglGetTextureImage
 * Signature: (IIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglGetTextureImage__IIIIILjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglGetTextureImage
 * Signature: (IIIIIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglGetTextureImage__IIIIIILjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedBufferData
 * Signature: (IJI)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedBufferData__IJI
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     com_longlinkislong_gloop_dsa_NativeDSA
 * Method:    nglNamedBufferStorage
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_longlinkislong_gloop_dsa_NativeDSA_nglNamedBufferStorage__ILjava_nio_ByteBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
